PRODUCTS_DATA = [
    {
        "name": "Camiseta Naruto Uzumaki",
        "description": "Camiseta fitness inspirada em Naruto, com visual geek para treino e lifestyle.",
        "price": 89.90,
        "stock": 50,
        "category": "camisetas",
        "image_url": "/products/camiseta-naruto-uzumaki.png",
        "legacy_names": [],
    },
    {
        "name": "Camiseta Naruto Masculina",
        "description": "Camiseta masculina Naruto com estampa premium e tecido confortavel.",
        "price": 94.90,
        "stock": 45,
        "category": "camisetas",
        "image_url": "/products/camiseta-naruto-masculina.png",
        "legacy_names": ["Camiseta Naruto Cole\u00e7\u00e3o Ninja", "Camiseta Naruto Cole\u00c3\u00a7\u00c3\u00a3o Ninja"],
    },
    {
        "name": "Conjunto Naruto Ninja",
        "description": "Conjunto fitness Naruto com top e legging para treino com estilo anime.",
        "price": 179.90,
        "stock": 25,
        "category": "conjuntos",
        "image_url": "/products/conjunto-naruto-ninja.png",
        "legacy_names": ["Camiseta Jujutsu Kaisen Masculina"],
    },
    {
        "name": "Camiseta Itachi Uchiha",
        "description": "Camiseta Itachi Uchiha com visual escuro, premium e inspirado no cla Uchiha.",
        "price": 99.90,
        "stock": 40,
        "category": "camisetas",
        "image_url": "/products/camiseta-itachi-uchiha.png",
        "legacy_names": [],
    },
    {
        "name": "Camiseta Dragon Ball Saiyajin",
        "description": "Camiseta Dragon Ball com energia Saiyajin para treinos intensos.",
        "price": 109.90,
        "stock": 35,
        "category": "camisetas",
        "image_url": "/products/camiseta-dragon-ball-saiyajin.png",
        "legacy_names": ["Camiseta Shadow Saiyan"],
    },
    {
        "name": "Legging Dragon Ball",
        "description": "Legging fitness Dragon Ball com conforto, elasticidade e arte tematica.",
        "price": 139.90,
        "stock": 30,
        "category": "leggings",
        "image_url": "/products/legging-dragon-ball.png",
        "legacy_names": [],
    },
    {
        "name": "Legging Dragon Ball Saiyajin",
        "description": "Legging Dragon Ball Saiyajin para treinos de alta performance.",
        "price": 139.90,
        "stock": 30,
        "category": "leggings",
        "image_url": "/products/legging-dragon-ball.png",
        "legacy_names": ["Legging Dragon Ball Cole\u00e7\u00e3o Saiyajin", "Legging Dragon Ball Cole\u00c3\u00a7\u00c3\u00a3o Saiyajin"],
    },
    {
        "name": "Top Jujutsu Kaisen",
        "description": "Top esportivo Jujutsu Kaisen para treino, mobilidade e estilo anime.",
        "price": 79.90,
        "stock": 40,
        "category": "tops",
        "image_url": "/products/top-jujutsu-kaisen.png",
        "legacy_names": [],
    },
    {
        "name": "Top Jujutsu Kaisen Feminino",
        "description": "Top feminino Jujutsu Kaisen com acabamento premium e suporte para treino.",
        "price": 84.90,
        "stock": 35,
        "category": "tops",
        "image_url": "/products/top-jujutsu-kaisen-feminino.png",
        "legacy_names": [],
    },
    {
        "name": "Conjunto Attack on Titan",
        "description": "Conjunto Attack on Titan com top e legging para performance e atitude.",
        "price": 169.90,
        "stock": 25,
        "category": "conjuntos",
        "image_url": "/products/conjunto-attack-on-titan.png",
        "legacy_names": [],
    },
    {
        "name": "Conjunto Attack on Titan Elite",
        "description": "Conjunto Attack on Titan Elite com visual premium inspirado na tropa de exploracao.",
        "price": 169.90,
        "stock": 25,
        "category": "conjuntos",
        "image_url": "/products/conjunto-attack-on-titan.png",
        "legacy_names": [],
    },
    {
        "name": "Camiseta Attack on Titan",
        "description": "Camiseta Attack on Titan com arte marcante para treinos e uso casual.",
        "price": 99.90,
        "stock": 40,
        "category": "camisetas",
        "image_url": "/products/camiseta-attack-on-titan.png",
        "legacy_names": [],
    },
    {
        "name": "Camiseta Attack on Titan Feminina",
        "description": "Camiseta feminina Attack on Titan com visual premium e modelagem confortavel.",
        "price": 104.90,
        "stock": 35,
        "category": "camisetas",
        "image_url": "/products/camiseta-attack-on-titan-feminina.png",
        "legacy_names": [],
    },
]
