PRODUCTS_DATA = [
    {
        "name": "Conjunto Dourado Orgânico",
        "description": "Colar, brinco e anel dourados com acabamento orgânico e brilho sofisticado.",
        "price": 237.00,
        "stock": 12,
        "category": "conjuntos",
        "image_url": "/products/charme/conjunto-dourado-caixa.jpeg",
        "legacy_names": [],
    },
    {
        "name": "Brincos Orgânicos Dourados",
        "description": "Brincos dourados com formas fluidas para composições elegantes.",
        "price": 129.00,
        "stock": 18,
        "category": "brincos",
        "image_url": "/products/charme/brincos-organicos-dourados.jpeg",
        "legacy_names": [],
    },
    {
        "name": "Corrente e Brincos Dourados",
        "description": "Corrente robusta com brincos dourados para um visual marcante e refinado.",
        "price": 215.00,
        "stock": 10,
        "category": "colares",
        "image_url": "/products/charme/corrente-e-brincos-dourados.jpeg",
        "legacy_names": [],
    },
    {
        "name": "Colares Escapulário",
        "description": "Colares dourados em camadas com escapulários delicados.",
        "price": 156.00,
        "stock": 16,
        "category": "colares",
        "image_url": "/products/charme/colares-escapulario.jpeg",
        "legacy_names": [],
    },
    {
        "name": "Conjunto Prata Ponto de Luz",
        "description": "Conjunto prateado com brilho delicado para ocasiões especiais.",
        "price": 220.00,
        "stock": 8,
        "category": "prata",
        "image_url": "/products/charme/conjunto-prata-ponto-luz.jpeg",
        "legacy_names": [],
    },
    {
        "name": "Conjunto Coração Dourado",
        "description": "Colares e brincos dourados com detalhes de coração e pontos de luz.",
        "price": 198.00,
        "stock": 10,
        "category": "conjuntos",
        "image_url": "/products/charme/conjunto-coracao-dourado.jpeg",
        "legacy_names": [],
    },
    {
        "name": "Conjunto Vermelho e Dourado",
        "description": "Acessórios em vermelho profundo com corrente dourada para looks de presença.",
        "price": 185.00,
        "stock": 9,
        "category": "conjuntos",
        "image_url": "/products/charme/conjunto-vermelho-dourado.jpeg",
        "legacy_names": [],
    },
    {
        "name": "Corrente Laminada Dourada",
        "description": "Corrente dourada laminada com acabamento luminoso e elegante.",
        "price": 215.00,
        "stock": 14,
        "category": "colares",
        "image_url": "/products/charme/corrente-laminada-dourada.jpeg",
        "legacy_names": [],
    },
]
