PRODUCTS_DATA = [
    {
        "name": "Conjunto Dourado Organico",
        "description": "Colar, brinco e anel dourados com acabamento organico e brilho sofisticado.",
        "price": 237.00,
        "stock": 12,
        "category": "colares",
        "image_url": "/products/charme/conjunto-dourado-caixa.jpeg",
        "legacy_names": ["Conjunto Dourado Orgânico"],
    },
    {
        "name": "Brincos Organicos Dourados",
        "description": "Brincos dourados com formas fluidas para composicoes elegantes.",
        "price": 129.00,
        "stock": 18,
        "category": "brincos",
        "image_url": "/products/charme/brincos-organicos-dourados.jpeg",
        "legacy_names": ["Brincos Orgânicos Dourados"],
    },
    {
        "name": "Corrente e Brincos Dourados",
        "description": "Corrente robusta com brincos dourados para um visual marcante e refinado.",
        "price": 215.00,
        "stock": 10,
        "category": "colares",
        "image_url": "/products/charme/corrente-e-brincos-dourados.jpeg",
        "legacy_names": [],
    },
    {
        "name": "Pingente Escapulario",
        "description": "Pingente escapulario delicado em banho dourado para composicoes classicas.",
        "price": 156.00,
        "stock": 16,
        "category": "pingentes",
        "image_url": "/products/charme/colares-escapulario.jpeg",
        "legacy_names": ["Colares Escapulário"],
    },
    {
        "name": "Colar Ponto de Luz Prata",
        "description": "Colar prateado com ponto de luz delicado para ocasioes especiais.",
        "price": 220.00,
        "stock": 8,
        "category": "colares",
        "image_url": "/products/charme/conjunto-prata-ponto-luz.jpeg",
        "legacy_names": ["Conjunto Prata Ponto de Luz"],
    },
    {
        "name": "Presente Coracao Dourado",
        "description": "Selecao dourada com detalhes de coracao para presentear com elegancia.",
        "price": 198.00,
        "stock": 10,
        "category": "presentes",
        "image_url": "/products/charme/conjunto-coracao-dourado.jpeg",
        "legacy_names": ["Conjunto Coração Dourado"],
    },
    {
        "name": "Conjunto Vermelho Sale",
        "description": "Acessorios em vermelho profundo com corrente dourada em condicao especial.",
        "price": 185.00,
        "stock": 9,
        "category": "sale",
        "image_url": "/products/charme/conjunto-vermelho-dourado.jpeg",
        "legacy_names": ["Conjunto Vermelho e Dourado"],
    },
    {
        "name": "Pulseira Laminada Dourada",
        "description": "Pulseira dourada laminada com acabamento luminoso e elegante.",
        "price": 215.00,
        "stock": 14,
        "category": "pulseiras",
        "image_url": "/products/charme/corrente-laminada-dourada.jpeg",
        "legacy_names": ["Corrente Laminada Dourada"],
    },
    {
        "name": "Anel Organico Dourado",
        "description": "Anel dourado com desenho organico e acabamento premium.",
        "price": 119.90,
        "stock": 10,
        "category": "aneis",
        "image_url": "/products/charme/conjunto-dourado-caixa.jpeg",
        "legacy_names": [],
    },
]
